=== llubu/ReactOS-Mirror/trunk/reactos/tools/rbuild/project.dtd
<!-- $Id$ -->
<!ENTITY % CIdentifier "CDATA">
	<!-- a C identifier -->
<!ENTITY % Text "CDATA">
    <!-- used for titles etc. -->

<!-- XInclude patch -->

<!ELEMENT xi:include (xi:fallback)*>
<!ATTLIST xi:include
	href %Text; #REQUIRED
>

<!ELEMENT xi:fallback (xi:include)>

<!-- rbuild project DTD -->

<!ELEMENT bootstrap EMPTY>
<!ATTLIST bootstrap
	base      %Text; #IMPLIED
	nameoncd  %Text; #IMPLIED
>

<!ELEMENT cdfile (#PCDATA)>
<!ATTLIST cdfile
	base      %Text; #IMPLIED
	nameoncd  %Text; #IMPLIED
>

<!ELEMENT compilerflag (#PCDATA)>

<!ELEMENT define EMPTY>
<!ATTLIST define
	name  %CIdentifier; #REQUIRED
	value %Text;        #IMPLIED
>

<!ELEMENT directory (directory*|group*|file*|if*|module+|pch*|xi:include*)+>
<!ATTLIST directory
	name %Text; #REQUIRED
>

<!ELEMENT file (#PCDATA)>
<!ATTLIST file
	first (true|false) "false"
>

<!ELEMENT group (cdfile*|directory*|file*|property*)+>

<!ELEMENT if (compilerflag*|define*|directory*|file*|if*|group*|property*)+>
<!ATTLIST if
	property %CIdentifier; #REQUIRED
	value    %Text;        #REQUIRED
>

<!ELEMENT include (#PCDATA)>
<!ATTLIST include
	base %Text; #IMPLIED
>

<!ELEMENT importlibrary EMPTY>
<!ATTLIST importlibrary
	definition %Text; #REQUIRED
>

<!ELEMENT library (#PCDATA)>

<!ELEMENT linkerflag (#PCDATA)>

<!ELEMENT linkerscript (#PCDATA)>
<!ATTLIST linkerscript
	base %Text; #IMPLIED
>

<!ELEMENT module (bootstrap*|importlibrary*|define*|include*|library*|directory*|file*|linkerflag*|linkerscript?)*>
<!ATTLIST module
	if	%Text; #IMPLIED
	ifnot	%Text; #IMPLIED
	name	%CIdentifier; #IMPLIED
	type	(buildtool|staticlibrary|objectlibrary|kernel|kernelmodedll|kernelmodedriver|nativedll|win32dll|win32cui|win32gui|bootloader|bootsector|iso|test|rpcserver|rpcclient|alias) #REQUIRED
	extension	%CIdentifier; #IMPLIED
	entrypoint	%CIdentifier; #IMPLIED
	baseaddress	%CIdentifier; #IMPLIED
	mangledsymbols	%Text; #IMPLIED
	underscoresymbols	(true|false) "false"
	installbase	%Text; #IMPLIED
	installname	%Text; #IMPLIED
	usewrc		%Text; #IMPLIED
	allowwarnings	(true|false) "false"
	aliasof %Text; #IMPLIED
>

<!ELEMENT pch (#PCDATA)>

<!ELEMENT project (compilerflag*|define*|group*|if*|include*|directory*|xi:include*)+>
<!ATTLIST project
	name      %Text;  #FIXED "ReactOS"
	makefile  %Text;  #FIXED "makefile.auto"
	xmlns:xi  %Text;  #FIXED "http://www.w3.org/2001/XInclude"
>

<!ELEMENT property EMPTY>
<!ATTLIST property
	name	%CIdentifier;	#REQUIRED
	value	%Text;		#REQUIRED
>

<!ELEMENT symbol (#PCDATA)>
<!ATTLIST symbol
	newname %Text; #IMPLIED
>

<!-- EOF -->

=== llubu/ReactOS-Mirror/trunk/reactos/ReactOS.xml
<?xml version="1.0"?>
<!DOCTYPE project SYSTEM "tools/rbuild/project.dtd">
<project name="ReactOS" makefile="makefile.auto" xmlns:xi="http://www.w3.org/2001/XInclude">
	<xi:include href="config.xml">
		<xi:fallback>
			<xi:include href="config.template.xml" />
		</xi:fallback>
	</xi:include>

	<xi:include href="baseaddress.xml" />

	<define name="_M_IX86" />
	<if property="MP" value="1">
		<define name="CONFIG_SMP" value="1" />
	</if>
	<if property="DBG" value="1">
		<define name="DBG" value="1" />
		<property name="DBG_OR_KDBG" value="true" />
	</if>
	<if property="DBG" value="0">
		<compilerflag>-Os</compilerflag>
		<compilerflag>-Wno-strict-aliasing</compilerflag>
		<compilerflag>-ftracer</compilerflag>
		<compilerflag>-momit-leaf-frame-pointer</compilerflag>
		<compilerflag>-mpreferred-stack-boundary=2</compilerflag>
	</if>
	<if property="KDBG" value="1">
		<define name="KDBG" value="1" />
		<property name="DBG_OR_KDBG" value="true" />
	</if>
	<compilerflag>-Wpointer-arith</compilerflag>

	<include>include</include>
	<include>include/reactos</include>
	<include>include/libs</include>
	<include>include/drivers</include>
	<include>include/subsys</include>
	<include>w32api/include</include>
	<include>w32api/include/crt</include>
	<include>w32api/include/ddk</include>

	<directory name="apps">
		<xi:include href="apps/directory.xml" />
	</directory>
	<directory name="boot">
		<xi:include href="boot/boot.xml" />
	</directory>
	<directory name="bootdata">
		<xi:include href="bootdata/bootdata.xml" />
	</directory>
	<directory name="drivers">
		<xi:include href="drivers/directory.xml" />
	</directory>
	<directory name="hal">
		<xi:include href="hal/directory.xml" />
	</directory>
	<directory name="include">
		<xi:include href="include/directory.xml" />
	</directory>
	<directory name="lib">
		<xi:include href="lib/directory.xml" />
	</directory>
	<directory name="media">
		<xi:include href="media/directory.xml" />
	</directory>
	<directory name="modules">
		<xi:include href="modules/directory.xml" />
	</directory>
	<directory name="ntoskrnl">
		<xi:include href="ntoskrnl/ntoskrnl.xml" />
	</directory>
	<directory name="regtests">
		<xi:include href="regtests/directory.xml" />
	</directory>
	<directory name="services">
		<xi:include href="services/directory.xml" />
	</directory>
	<directory name="subsys">
		<xi:include href="subsys/directory.xml" />
	</directory>
</project>
